"""Export full-split frozen-F top256 candidates for adapted LMD.

Training/development use online clean/fog/rain/snow generated by the existing
project weather pipeline. Benchmark mode reads the fixed OPV2V / OPV2V-W test
sets with online weather augmentation disabled.
"""
from __future__ import annotations

import argparse
import copy
import json
from pathlib import Path

import numpy as np
import torch

from gspr_communication.runtime import device, seed_all, sha256, verify_frozen, write_json
from gspr_evidence import runtime as er
from gspr_evidence.stage3_trace import trace_branch
from local_fusion_v3 import runtime as v3rt
from opencood.tools.train_utils import to_device
from opencood.utils import box_utils

from local_fusion_detector_adaptation.candidate_audit import (
    _load_arm, candidate_ids, geometry_ids,
)

WEATHERS = ("clean", "fog", "rain", "snow")
DEFAULT_BENCHMARK_ROOTS = {
    "clean": "/data/scd/datasets/opv2v_official_data_dumping/test",
    "fog": "/data/cjm/datasets/opv2v-w/fog/test",
    "rain": "/data/cjm/datasets/opv2v-w/rain/test",
    "snow": "/data/cjm/datasets/opv2v-w/snow/test",
}


def _scene_map(indices, boundaries):
    ends = np.asarray(boundaries, dtype=np.int64)
    if not len(ends):
        raise ValueError("Empty scene boundaries")
    return {str(int(index)): int(np.searchsorted(ends, int(index), side="right"))
            for index in indices}


def _dataset(hypes, options, split, weather, smoke, benchmark_roots):
    if split in ("train", "validation"):
        ds, loader, indices = er.make_loader(
            hypes, options, train=(split == "train"), weather=weather, smoke=smoke)
        branch = "clean" if weather == "clean" else "weather"
        data_root = hypes["root_dir" if split == "train" else "validate_dir"]
        return ds, loader, indices, branch, str(Path(data_root).resolve())
    local = copy.deepcopy(hypes)
    local["validate_dir"] = benchmark_roots[weather]
    local.pop("weather_augmentation", None)
    ds, loader, indices = er.make_loader(local, options, train=False,
                                         weather="clean", smoke=smoke)
    return ds, loader, indices, "clean", str(Path(benchmark_roots[weather]).resolve())


def export(args):
    verify_frozen()
    run = Path(args.run).resolve()
    pilot = json.loads((run / "protocol.json").read_text(encoding="utf-8"))
    options, hypes = er.load_config(args.v3_config, args.frontend_config)
    target = device()
    model, frontend_hash = er.load_model(hypes, options, args.frontend_checkpoint, target)
    model.requires_grad_(False).eval()
    if frontend_hash != pilot["frontend_sha256"]:
        raise ValueError("Frontend differs from frozen F pilot")
    contract = v3rt.contract(options, args.frontend_config, frontend_hash)
    v3_hash = sha256(args.v3_checkpoint)
    if contract != pilot["v3_contract"] or v3_hash != pilot["v3_checkpoint_sha256"]:
        raise ValueError("v3 configuration/checkpoint differs from frozen pilot")
    source, checkpoint = v3rt.load(args.v3_checkpoint, contract, target)
    if checkpoint["variant"] != "residual":
        raise ValueError("Expected frozen residual v3 checkpoint")
    f_path = run / "F.pth"
    arm = _load_arm(f_path, source, model.engine.base, target, False)
    arm.requires_grad_(False).eval()
    del source

    benchmark_roots = dict(DEFAULT_BENCHMARK_ROOTS)
    for weather in WEATHERS:
        value = getattr(args, f"{weather}_test_root", None)
        if value:
            benchmark_roots[weather] = value

    output = Path(args.output).resolve()
    output.mkdir(parents=True, exist_ok=False)
    report = {
        "schema": 1,
        "method": "adapted_lmd_core",
        "split": args.split,
        "candidate_pool": "geometry-valid top256 by frozen F score before NMS",
        "full_split": args.smoke == 0,
        "smoke_frames": int(args.smoke),
        "frontend_sha256": frontend_hash,
        "v3_checkpoint_sha256": v3_hash,
        "arm_sha256": {"F": sha256(f_path)},
        "implementation_sha256": sha256(Path(__file__).resolve()),
        "row_semantics": "fixed decoded F candidate; GT quality is training/evaluation label only",
        "conditions": {},
    }
    write_json(output / "protocol.json", report)

    for weather_index, weather in enumerate(WEATHERS):
        seed_all(args.seed + weather_index)
        ds, loader, indices, branch, data_root = _dataset(
            hypes, options, args.split, weather, args.smoke, benchmark_roots)
        scene_map = _scene_map(indices, ds.len_record)
        pp = ds.post_processor
        threshold = float(pp.params["target_args"]["score_threshold"])
        if abs(threshold - 0.2) > 1e-8:
            raise ValueError(f"Unexpected detector score threshold: {threshold}")
        box_order = str(pp.params["order"])
        folder = output / weather
        folder.mkdir()
        total = original_total = overflow = zero_frames = 0
        with torch.no_grad(), (folder / "candidate_rows.jsonl").open(
                "w", encoding="utf-8") as row_stream, (
                folder / "frame_targets.jsonl").open(
                "w", encoding="utf-8") as target_stream:
            for position, batch in enumerate(loader):
                batch = to_device(batch, target)
                sample = int(batch["ego"]["communication_sample_index"][0])
                if sample != int(indices[position]):
                    raise RuntimeError("Loader order differs from extraction indices")
                ctx = v3rt.context(model, batch["ego"], branch, verify=(position == 0))
                prediction, _ = arm.predict(model.engine.base, ctx["levels"])
                trace = trace_branch(ds, batch, prediction)
                valid = geometry_ids(trace)
                ids = candidate_ids(trace, 0.0, 256, valid)
                original = candidate_ids(trace, 0.2, None, valid)
                total += len(ids)
                original_total += len(original)
                overflow += int(len(original) > len(ids))
                zero_frames += int(len(ids) == 0)
                gt = np.asarray(trace["gt"], dtype=np.float32)
                target_stream.write(json.dumps({
                    "weather": weather, "sample_index": sample,
                    "scene": scene_map[str(sample)],
                    "gt_bev_corners": gt[:, :4, :2].tolist() if len(gt) else [],
                }) + "\n")
                if len(ids):
                    fused = np.asarray(trace["corners"], dtype=np.float32)[ids]
                    within = box_utils.get_mask_for_boxes_within_range_torch(
                        torch.as_tensor(fused, dtype=torch.float32)).cpu().numpy()
                    ious = np.asarray(trace["ious"], dtype=np.float32)
                    quality = (ious[ids].max(axis=1) if ious.shape[1]
                               else np.zeros(len(ids), dtype=np.float32))
                    decoded = np.asarray(trace["decoded"], dtype=np.float32)[ids]
                    scores = np.asarray(trace["scores"], dtype=np.float32)[ids]
                    for local_index, cid in enumerate(ids):
                        row_stream.write(json.dumps({
                            "weather": weather,
                            "sample_index": sample,
                            "scene": scene_map[str(sample)],
                            "candidate_id": int(cid),
                            "score": float(scores[local_index]),
                            "max_gt_iou": float(quality[local_index]),
                            "fused_decoded_box": decoded[local_index].tolist(),
                            "fused_bev_corners": fused[local_index, :4, :2].tolist(),
                            "within_range": bool(within[local_index]),
                        }) + "\n")
                if position == 0 or (position + 1) % 50 == 0:
                    print(f"LMD {args.split} {weather}: {position + 1}/{len(indices)}",
                          flush=True)
        condition = {
            "frames": len(indices), "sample_indices": [int(x) for x in indices],
            "scene_map": scene_map, "data_root": data_root,
            "online_weather": bool(args.split != "benchmark" and weather != "clean"),
            "box_order": box_order,
            "original_score_threshold": threshold,
            "nms_iou_threshold": float(pp.params["nms_thresh"]),
            "top256_candidates": int(total),
            "original_scorepass_candidates": int(original_total),
            "original_scorepass_exceeds_top256_frames": int(overflow),
            "empty_top256_frames": int(zero_frames),
        }
        report["conditions"][weather] = condition
        write_json(folder / "summary.json", condition)
        del ds, loader
    if sha256(Path(__file__).resolve()) != report["implementation_sha256"]:
        raise RuntimeError("Extraction source changed during execution")
    write_json(output / "candidate_audit.json", report)
    verify_frozen()
    print("LMD CANDIDATE EXTRACTION COMPLETE:", output, flush=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run", required=True)
    parser.add_argument("--v3-config", default="local_fusion_v3/experiment.yaml")
    parser.add_argument("--frontend-config", required=True)
    parser.add_argument("--frontend-checkpoint", required=True)
    parser.add_argument("--v3-checkpoint", required=True)
    parser.add_argument("--split", choices=("train", "validation", "benchmark"), required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--smoke", type=int, default=0,
                        help="First N frames per weather; 0 means full split")
    parser.add_argument("--seed", type=int, default=20260929)
    for weather, default in DEFAULT_BENCHMARK_ROOTS.items():
        parser.add_argument(f"--{weather}-test-root", default=default)
    args = parser.parse_args()
    if args.smoke < 0:
        parser.error("--smoke must be >= 0")
    export(args)


if __name__ == "__main__":
    main()
